ROOT_PATH = None
PYTHON_PATH = None
TOKEN = None
CHAT_ID = None
LANG = None
START_TRADE_BOT = None
BINANCE_API_KEY = None
BINANCE_API_SECRET = None
COIN_LIST = None
CURRENCY = None
OER_KEY = None
TLD = None
RAW_ARGS = ""

TG_UPDATE_BROADCASTED_BEFORE = False
BTB_UPDATE_BROADCASTED_BEFORE = False

BOT = None
CHAT = None
